

route_stock:
  resource: "routes/route_stock.yml"
  prefix: "/anis/stock"
update_stock_hattaa:
 path: /update_stock_hattaa
 methods: GET
 defaults:
   _controller: Anis\Stockmanagement\controller\StockManagement::update_stock_hattaa
   _disable_module_prefix: true
   _legacy_controller: StockManagement
   _legacy_link: StockManagement

handle_upload:
 path: /handle_upload
 methods: POST
 defaults:
   _controller: Anis\Stockmanagement\controller\StockManagement::handle_upload
   _disable_module_prefix: true
   _legacy_controller: StockManagement
   _legacy_link: StockManagement   

export_stock:
 path: /export_stock
 methods: GET
 defaults:
   _controller: Anis\Stockmanagement\controller\ExportStock::export_stock
   _disable_module_prefix: true
   _legacy_controller: ExportStock
   _legacy_link: ExportStock      

getLogContent:
 path: /getLogContent
 methods: GET
 defaults:
   _controller: Anis\Stockmanagement\controller\LogsController::getLogContent
   _disable_module_prefix: true
   _legacy_controller: LogsController
   _legacy_link: LogsController   

   